routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\NotLoggedIn;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AllUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OptionController;
use App\Http\Controllers\OptionValueController;
use App\Http\Controllers\AttributeController;
use App\Http\Controllers\ProductAttributeController;
// use App\Http\Controllers\RolePermissionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login',[UserController::class,'login'])->middleware('notLoggedIn');

Route::post('/check',[UserController::class,'check'])->name('check');
Route::get('/logout',[UserController::class,'logout']);

Route::group(['middleware'=>'authCheck'], function (){
    Route::get('/admin',[UserController::class,'admin']);

    Route::resource('/admin/profile',ProfileController::class);
    Route::resource('/admin/users',AllUserController::class);
    Route::resource('/admin/roles',RoleController::class);
    Route::resource('/admin/permissions',PermissionController::class);
    Route::get('/admin/products/get-option-values',[ProductController::class,'getOptionValues']);
    Route::resource('/admin/products',ProductController::class);
   
    Route::resource('/admin/options',OptionController::class);
    Route::resource('/admin/option-values',OptionValueController::class);
    Route::resource('/admin/attributes',AttributeController::class);
    Route::resource('/admin/attribute-values',ProductAttributeController::class);
    // Route::resource('/admin/role_permissions',RolePermissionController::class);
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Role extends Model
{
    protected $table = 'roles';
    use HasFactory;
    
    public function rolePermissions(){
        return $this->hasMany('App\Models\RolePermission','role_id','id');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Permission;
use App\Models\RolePermission;

class RoleController extends Controller
{
    public function index(){
        $role = Role::all();
        $role_permission = RolePermission::with('all_permissions')
        ->get()
        ->toArray();
        // echo "<pre>";
        // print_r($role_permission);
        // exit();
        return view('admin/roles/listing',compact('role','role_permission'));
    }

    public function create(){
        $permission = Permission::all();
        return view('admin/roles/add',compact('permission'));
    }

    public function store(Request $req){
        $req->validate([
            'role'=>'required',
        ]);

        $role = new Role;
        $role->role = $req->role;

        $role->save();

        $role_id = $role->id;
        foreach($req->permissions as $key => $permissions){
            $permission = [];
            $permission['role_id'] = $role_id;
            $permission['permission_id'] = $permissions;
     
            RolePermission::insert($permission);
        }
        return redirect('/admin/roles')->with('success','Role is successfully added!');
    }

    public function show($id){

    }

    public function edit($id){
        $roles = Role::find($id);
        $permission = Permission::all();
        $role_permission = RolePermission::where('role_id','=',$id)->get();
        return view('admin/roles/edit',compact('roles','permission','role_permission'));
    }

    public function update(Request $req,$id){
        $req->validate([
            'role'=>'required',
        ]);

        $roles = Role::find($id);
        $roles->role = $req->role;

        $roles->save();
        $role_permission = RolePermission::where('role_id','=',$id);
        $role_permission->delete();
        $roles_id = $roles->id;
        foreach($req->permissions as $key => $permissions){
            $permission = [];
            $permission['role_id'] = $roles_id;
            $permission['permission_id'] = $permissions;
     
            RolePermission::where('role_id','=',$id)->insert($permission);
        }
        return redirect('/admin/roles')->with('success','Role is successfully updated!');
    }

    public function destroy($id){
        $roles = Role::find($id);
        $roles->delete();
        $role_permission = RolePermission::where('role_id','=',$id);
        $role_permission->delete();
        return redirect('/admin/roles')->with('success','Role is successfully deleted!');

    }

}

resources/views/admin/roles/add.blade.php
@extends('layouts/admin_web')
<title>Skriper | Roles | Add</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Add Role</h1>
                </div>
                <div class="card">
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Add role</h5></div>
                <form action="{{ route('roles.store') }}" method="POST">
                    @csrf
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Role</label>
                        <div class="input-group has-validation">
                        <input type="text" class="form-control" name="role">
                        </div>
                        @error('role')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-6 position-relative">
                        <label for="validationTooltip03" class="form-label">Permissions</label>
                        <table class="table table-responsive-sm table-hover table-bordered text-center">
                            <div class="input-group has-validation">
                                <thead class="table-dark">
                                    <tr>
                                        <th>#</th>
                                        <th>Permission</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($permission as $permissions)
                                    <tr>
                                        <div class="me-2">
                                            <td><input type="checkbox" value="{{$permissions->id}}" name="permissions[]"></td>
                                            <td><label for="">{{$permissions->permission_key}}</label></td>
                                        </div>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </div>
                        </table>
                    </div>
                    <div class="col-sm-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-plus"></i> Add</button>
                    </div>
                </form>  
                </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts/admin_web')
<title>Skriper | Roles | Update</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Update Role</h1>
                </div>
                <div class="card">
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Edit role</h5></div>
                <form action="{{ route('roles.update' , $roles->id) }}" method="POST">
                @csrf
                @method('PATCH')
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Role</label>
                        <div class="input-group has-validation">
                        <input type="text" class="form-control" name="role" value="{{$roles->role}}">
                        </div>
                        @error('role')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-6 position-relative">
                        <label for="validationTooltip03" class="form-label">Permissions</label>
                        <table class="table table-responsive-sm table-hover table-bordered text-center">
                            <div class="input-group has-validation">
                            <thead class="table-dark">
                            <tr>
                                <th>#</th>
                                <th>Permission</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($permission as $permissions)
                                <tr>
                                    <div class="me-2">
                                        <td>
                                            <input type="checkbox" value="{{$permissions->id}}" name="permissions[]" 
                                            <?php foreach($role_permission as $role_permissions){
                                                if($permissions->id == $role_permissions->permission_id){
                                                    echo "checked";
                                                } } ?> 
                                            >
                                        </td>
                                        <td>
                                            <label for="">{{$permissions->permission_key}}</label>
                                        </td>
                                    </div>
                                </tr>
                                @endforeach
                            </tbody>
                            </div>
                        </table>
                        @error('permissions')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-edit"> </i> Update</button>
                    </div>
                </form>
                </div>
@endsection

resources/views/admin/roles/listing.blade.php
@extends('layouts/admin_web')
<title>Skriper | Roles</title>

@section('content')
            <div class="col-12 mb-3 d-flex justify-content-between">
                <h1>Roles</h1>
                    <?php 
                        foreach (session()->get('permissionKey') as $key) {
                            if($key['permission_key'] == 'role-add'){ 
                    ?>
                <a href="{{ route('roles.create') }}"><button class="btn btn-info text-light"><i class="fas fa-plus"></i> Add</button></a>
                    <?php } }  ?>
                </div>
                @if(Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{Session::get('success')}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                @endif
                <div class="card">
                <div class="headeing-content"><h5><i class="fal fa-list-ul me-1"></i> Role List</h5></div>
                <div class="col-12">    
                <table id="userCategories" class="table table-responsive-sm table-hover table-bordered text-center">
                    <thead class="table-dark">
                        <tr>
                            <th>Id</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="table-secondary text-secondary">
                    @foreach($role as $roles)
                        <tr>
                            
                            <td>{{$roles->id}}</td>
                            <td>{{$roles->role}}</td>
                            <td class="d-flex justify-content-center">
                            <?php 
                                foreach (session()->get('permissionKey') as $key) {
                                    if($key['permission_key'] == 'role-update'){ 
                            ?>
                            <a href="{{ route('roles.edit', $roles->id) }}" class="my-auto me-2"><button class="btn btn-success"><i class="fas fa-edit"></i> Edit </button></a>
                            <?php 
                                    }
                                    if($key['permission_key'] == 'role-delete'){ 
                            ?>
                            <form action="{{ route('roles.destroy', $roles->id) }}" method="post" class="my-auto">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button>
                            </form>  
                            <?php } } ?>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
                </div>
@endsection