routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\NotLoggedIn;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AllUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OptionController;
use App\Http\Controllers\OptionValueController;
use App\Http\Controllers\AttributeController;
use App\Http\Controllers\ProductAttributeController;
// use App\Http\Controllers\RolePermissionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login',[UserController::class,'login'])->middleware('notLoggedIn');

Route::post('/check',[UserController::class,'check'])->name('check');
Route::get('/logout',[UserController::class,'logout']);

Route::group(['middleware'=>'authCheck'], function (){
    Route::get('/admin',[UserController::class,'admin']);

    Route::resource('/admin/profile',ProfileController::class);
    Route::resource('/admin/users',AllUserController::class);
    Route::resource('/admin/roles',RoleController::class);
    Route::resource('/admin/permissions',PermissionController::class);
    Route::get('/admin/products/get-option-values',[ProductController::class,'getOptionValues']);
    Route::resource('/admin/products',ProductController::class);
   
    Route::resource('/admin/options',OptionController::class);
    Route::resource('/admin/option-values',OptionValueController::class);
    Route::resource('/admin/attributes',AttributeController::class);
    Route::resource('/admin/attribute-values',ProductAttributeController::class);
    // Route::resource('/admin/role_permissions',RolePermissionController::class);
});

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    use HasFactory;
    protected $table = 'attributes';


}

app/Http/Controllers/AttributeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Attribute;

class AttributeController extends Controller
{
    public function index(){
        $attribute = Attribute::all();

        return view('/admin/attributes/listing',compact('attribute'));
    }

    public function create(){
        return view('/admin/attributes/add');
    }

    public function store(Request $req){
        $req->validate([
            'attribute_name'=>'required',
        ]);

        $attribute = new Attribute;
        $attribute->attribute_name = $req->attribute_name;
        $attribute->sort_order = 0;
        $attribute->save();

        return redirect('/admin/attributes')->with('success','Attribute is successfully added!');
    }

    public function edit($id){
        $attribute = Attribute::find($id);
        // echo '<pre>';
        // print_r($attribute);
        // exit();

        return view('/admin/attributes/edit',compact('attribute'));
    }

    public function update(Request $req,$id){
        $req->validate([
            'attribute_name'=>'required',
        ]);

        $attribute = Attribute::find($id);
        $attribute->attribute_name = $req->attribute_name;
        $attribute->sort_order = 0;
        $attribute->save();

        return redirect('/admin/attributes')->with('success','Attribute is successfully updated!');
    }

    public function destroy($id){
        $attribute = Attribute::find($id);
        $attribute->delete();

        return redirect('/admin/attributes')->with('success','Attribute is successfully deleted!');
    }
}

resources/views/admin/attributes/add.blade.php
@extends('layouts/admin_web')
<title>Skriper | Attributes | Add</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Add Attributes</h1>
                </div>
                <div class="card">
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Add attribute</h5></div>
                <form action="{{ route('attributes.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Attibute Name</label>
                    <div class="input-group has-validation">
                    <input type="text" class="form-control" name="attribute_name">
                    </div>
                    @error('attribute_name')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                    <div class="col-sm-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-plus"></i> Add</button>
                    </div>
                </form> 
                </div>
@endsection

resources/views/admin/attributes/edit.blade.php
@extends('layouts/admin_web')
<title>Skriper | Attributes | Update</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Update Attributes</h1>
                </div>
                <form action="{{ route('attributes.update' , $attribute['id']) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label">Attibute Name</label>
                    <div class="input-group has-validation">
                    <input type="text" class="form-control" name="attribute_name" value="{{$attribute['attribute_name']}}">
                    </div>
                    @error('attribute_name')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                    <div class="col-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-edit"> </i> Update</button>
                    </div>
                </form>
@endsection

resources/views/admin/attributes/listing.blade.php
@extends('layouts/admin_web')
<title>Skriper | Attributes</title>

@section('content')
                <div class="col-12 mb-3 d-flex justify-content-between">
                    <h1>Attributes</h1>
                        <?php 
                            foreach (session()->get('permissionKey') as $key) {
                                if($key['permission_key'] == 'attribute-add'){ 
                        ?>
                    <a href="{{ route('attributes.create') }}"><button class="btn btn-info text-light"><i class="fas fa-plus"></i> Add</button></a>
                        <?php } }  ?>
                </div>
                @if(Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{Session::get('success')}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                @endif
                <div class="card">
                    <div class="headeing-content"><h5><i class="fal fa-list-ul me-1"></i> Attribute List</h5></div>
                    <div class="col-12">    
                    <table id="userCategories" class="table table-responsive-sm table-hover table-bordered text-center">
                        <thead class="table-dark">
                            <tr>
                                <th>Id</th>
                                <th>Attribute Name</th>
                                <th>Sort Order</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody class="table-secondary text-secondary">
                            @foreach($attribute as $attributes)
                                <tr>
                                    <td>{{$attributes->id}}</td>
                                    <td>{{$attributes->attribute_name}}</td>
                                    <td>{{$attributes->sort_order}}</td>
                                    <td class="d-flex justify-content-center">
                                        <?php 
                                            foreach (session()->get('permissionKey') as $key) {
                                                if($key['permission_key'] == 'attribute-update'){ 
                                        ?>
                                        <a href="{{ route('attributes.edit', $attributes->id) }}" class="my-auto me-2"><button class="btn btn-success"><i class="fas fa-edit"></i> Edit </button></a>
                                        <?php 
                                                }
                                                if($key['permission_key'] == 'attribute-delete'){ 
                                        ?>
                                        <form action="{{ route('attributes.destroy', $attributes->id) }}" method="post" class="my-auto">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button>
                                        </form>  
                                        <?php } } ?>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                </div>

@endsection