routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\NotLoggedIn;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AllUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OptionController;
use App\Http\Controllers\OptionValueController;
use App\Http\Controllers\AttributeController;
use App\Http\Controllers\ProductAttributeController;
// use App\Http\Controllers\RolePermissionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login',[UserController::class,'login'])->middleware('notLoggedIn');

Route::post('/check',[UserController::class,'check'])->name('check');
Route::get('/logout',[UserController::class,'logout']);

Route::group(['middleware'=>'authCheck'], function (){
    Route::get('/admin',[UserController::class,'admin']);

    Route::resource('/admin/profile',ProfileController::class);
    Route::resource('/admin/users',AllUserController::class);
    Route::resource('/admin/roles',RoleController::class);
    Route::resource('/admin/permissions',PermissionController::class);
    Route::get('/admin/products/get-option-values',[ProductController::class,'getOptionValues']);
    Route::resource('/admin/products',ProductController::class);
   
    Route::resource('/admin/options',OptionController::class);
    Route::resource('/admin/option-values',OptionValueController::class);
    Route::resource('/admin/attributes',AttributeController::class);
    Route::resource('/admin/attribute-values',ProductAttributeController::class);
    // Route::resource('/admin/role_permissions',RolePermissionController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table='products';

    public function productImages(){
        return $this->hasMany('App\Models\ProductImage','product_id','id');
    } 

    public function productOption(){
        return $this->hasMany('App\Models\ProductOption','product_id','id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Option;
use App\Models\OptionValue;
use App\Models\ProductOption;
use App\Models\ProductOptionValue;
use App\Models\Attribute;
use App\Models\ProductAttribute;
use DB; 

class ProductController extends Controller
{
    public function index(){
        $product = Product::with(['productImages'])
        ->paginate(6);
        // ->get()->toArray();
        // echo '<pre>';
        // print_r($product);
        // exit();
        return view('/admin/products/listing',compact('product'));
    }

    public function show($id){
        $product = Product::with('productImages')->where('id','=',$id)->get();

        // echo '<pre>';
        // print_r($product);
        // exit();
        return view('/admin/products/view',compact('product'));
    }

    public function create(Request $req){
        // $productOptionValue = Product::with(['productOption','productOption.option','productOption.option.optionValue'])
        // ->get()
        // ->toArray();
        $option = Option::all();
        $attribute = Attribute::all();

        // echo '<pre>';
        // print_r($productOptionValue);
        // exit();
        return view('/admin/products/add',compact('option','attribute'));
    }

    public function store(Request $req){

        $req->validate([
            'product_name'=>'required',
            'product_description'=>'required',
            'price'=>'required',
            'link'=>'required',
            'product_image'=>'required',
            'option'=>'required',
            'option_value'=>'required',
            'attribute'=>'required',
            'attribute_value'=>'required',
        ]);
        $product = new Product;
        $product->product_name = $req->product_name;
        $product->product_description = $req->product_description;
        $product->price = $req->price;
        $product->link = $req->link;
        $product->save();

        $product_id = $product['id'];
        $price = $product['price'];
        if($req->hasfile('product_image')){
            foreach ($req->file('product_image') as $images) {
                $tempData = [];
                $tempData['product_id'] = $product_id;

                $ext = $images->getClientOriginalName();
                $name = time() . '.' . $ext;
                $images->storeAs('public/product_images/',$name);
                $tempData['product_images'] = $name;

                $tempData['is_featured'] = 0;

                ProductImage::insert($tempData);
            }
        }

        foreach ($req['option'] as $key => $option) {
            $productOption = new ProductOption;
            $productOption->product_id = $product_id;
            $productOption->option_id = $option;
            $productOption->save();

            $productOptionValue = new ProductOptionValue;
            $productOptionValue->product_id = $product_id;
            $productOptionValue->option_id = $option;
            $productOptionValue->product_option_id = $productOption->id;
            $productOptionValue->option_value_id = $req['option_value'][$key];
            $productOptionValue->price = $price;
            $productOptionValue->save();
        }

        foreach ($req->attribute as $key => $attribute) {
            $attributeValue = [];
            $attributeValue['product_id'] = $product_id;
            $attributeValue['attribute_id'] = $attribute;
            $attributeValue['attribute_value'] = $req->attribute_value[$key];

            ProductAttribute::insert($attributeValue);
        }

        return redirect('/admin/products')->with('success','Product is successfully added!');
    }

    public function edit($id){
        $products = Product::find($id);
        $product_images = ProductImage::where('product_id','=',$id)->get()->toArray();
        $option = Option::all();
        $productOption = ProductOption::where('product_id','=',$id)->get('option_id');
        $attribute = Attribute::all();
        $productAttribute = ProductAttribute::where('product_id','=',$id)->get();

        // echo '<pre>';
        // print_r($productOption);
        // exit();
        return view('/admin/products/edit',compact('products','product_images','option','productOption','attribute','productAttribute'));
    }

    public function update(Request $req,$id){
        $req->validate([
            'product_name'=>'required',
            'product_description'=>'required',
            'price'=>'required',
            'link'=>'required',
            'product_image'=>'required',
            'option'=>'required',
            'attribute'=>'required',
            'attribute_value'=>'required',
        ]);

        $product = Product::find($id);
        $product->product_name = $req->product_name;
        $product->product_description = $req->product_description;
        $product->price = $req->price;
        $product->link = $req->link;
        $product->save();

        $product_id = $product['id'];
        
        $productImage = ProductImage::where('product_id','=',$id);
        $productImage->delete();

        if($req->hasfile('product_image')){
            foreach ($req->file('product_image') as $images) {
                $tempData = [];
                $tempData['product_id'] = $product_id;

                $ext = $images->getClientOriginalName();
                $name = time() . '.' . $ext;
                $images->storeAs('public/product_images/',$name);
                $tempData['product_images'] = $name;

                $tempData['is_featured'] = 0;

                ProductImage::where('product_id','=',$id)->insert($tempData);
            }
        }
        
        ProductOption::where('product_id','=',$id)->delete();

        foreach ($req->option as $option) {
            $optionValue = [];
            $optionValue['product_id'] = $product_id;
            $optionValue['option_id'] = $option;
            
            ProductOption::where('product_id','=',$id)->insert($optionValue);
        }

        ProductAttribute::where('product_id','=',$id)->delete();

        foreach ($req->attribute as $key => $attribute) {
            $attributeValue = [];
            $attributeValue['product_id'] = $product_id;
            $attributeValue['attribute_id'] = $attribute;
            $attributeValue['attribute_value'] = $req->attribute_value[$key];

            ProductAttribute::insert($attributeValue);
        }

        return redirect('/admin/products')->with('success','Product is successfully updated!');
    }

    public function destroy($id){
        $product = Product::find($id);
        $product->delete();

        $productImage = ProductImage::where('product_id','=',$id);
        $productImage->delete();
        
        $optionValue = ProductOption::where('product_id','=',$id);
        $optionValue->delete();

        $productAttribute = ProductAttribute::where('product_id','=',$id);
        $productAttribute->delete();

        return redirect('/admin/products')->with('success','Product is successfully deleted!');
    }

    public function getOptionValues(Request $request){
        $option_id = $request->option_id;
        $optionValue= OptionValue::where("option_id",$option_id)->get();

        return response()->json(['optionValue'=>$optionValue]);
    }

}

resources/views/admin/products/add.blade.php
@extends('layouts/admin_web')
<title>Skriper | Product | Add</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Add Product</h1>
                </div>
                <div class="card">
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Add product</h5></div>
                <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Name</label>
                    <div class="input-group has-validation">
                    <input type="text" class="form-control" name="product_name">
                    </div>
                    @error('product_name')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Desciption</label>
                    <div class="input-group has-validation">
                    <textarea id="editor" class="form-control" name="product_description"></textarea>
                    </div>
                    @error('product_description')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Price</label>
                    <div class="input-group has-validation">
                    <input type="number" class="form-control" name="price">
                    </div>
                    @error('price')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Link</label>
                    <div class="input-group has-validation">
                    <input type="text" class="form-control" name="link">
                    </div>
                    @error('product_link')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Images</label>
                    <div class="input-group has-validation">
                    <input type="file" class="form-control" name="product_image[]">
                    <a class="btn btn-success text-light" onclick="createImage()">+ Add Another Image</a>
                    </div>
                    <div id="newElementId1"></div>
                    @error('product_image')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <br>
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Add attribute</h5></div>
                <div class="row position-relative clone alert alert-dismissible fade show pb-0 mb-0">
                    <div class="col-sm-5">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Attributes Name</label>
                        <div class="input-group has-validation">
                            <select name="attribute[]" class="form-control">
                                @foreach($attribute as $attributes)
                                    <option value="{{$attributes->id}}">{{$attributes->attribute_name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Attributes Value</label>
                        <div class="input-group has-validation">
                            <input type="text" class="form-control" name="attribute_value[]">
                        </div>
                    </div>
                    <div class="col-sm-1 mt-auto mx-auto">
                    <button type="button" class="rounded btn btn-danger" data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-trash"></i></button>
                    </div>
                    <div class="col-sm-1 mt-auto mx-auto">
                        <a class="btn btn-success checked text-light"><i class="fas fa-plus"></i></a>
                    </div>
                    @error('attribute')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="add-attribute-value"></div>
                <br>
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Add option</h5></div>
                <div class="row position-relative clone-option alert alert-dismissible fade show pb-0 mb-0">
                    <div class="col-sm-5 option">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Option Name</label>
                        <div class="input-group has-validation">
                            <select name="option[]" class="form-control" id="selectOption">
                                <option>Select Option</option>
                                    @foreach($option as $options)
                                        <option value="{{$options->id}}">{{$options->option_name}}</option>
                                    @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-5 option-value">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Option Value</label>
                        <div class="input-group has-validation">
                        <select name="option_value[]" class="form-control" id="selectOptionValue">
                                
                        </select>
                        </div>
                    </div>
                    <div class="col-sm-1 mt-auto mx-auto">
                    <button type="button" class="rounded btn btn-danger" data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-trash"></i></button>
                    </div>
                    <div class="col-sm-1 mt-auto mx-auto">
                        <a class="btn btn-success checked-option text-light"><i class="fas fa-plus"></i> </a>
                    </div>
                    @error('option')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="add-option-value"></div>
                    <div class="col-sm-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-plus"></i> Add</button>
                    </div>
                </form>
                </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts/admin_web')
<title>Skriper | Product | Update</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Update Product</h1>
                </div>
                <div class="card">
                <div class="headeing-content"><h5 class="m-auto"><i class="fal fa-list-ul me-1"></i> Edit product</h5></div>
                <form action="{{ route('products.update' , $products['id']) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Name</label>
                    <div class="input-group has-validation">
                    <input type="text" class="form-control" name="product_name" value="{{$products['product_name']}}">
                    </div>
                    @error('product_name')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Desciption</label>
                    <div class="input-group has-validation">
                    <textarea class="form-control" name="product_description">{{$products['product_description']}}</textarea>
                    </div>
                    @error('product_description')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Price</label>
                    <div class="input-group has-validation">
                    <input type="number" class="form-control" name="price" value="{{$products['price']}}">
                    </div>
                    @error('price')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Link</label>
                    <div class="input-group has-validation">
                    <input type="text" class="form-control" name="link" value="{{$products['link']}}">
                    </div>
                    @error('product_link')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Product Images</label>
                    <a class="btn btn-success text-light float-right" onclick="createImage()">+ Add Another Image</a>
                    <div class="input-group has-validation">
                    @foreach($product_images as $images)
                    <div class="alert alert-dismissible fade show p-0" style="width:100%;">
                        <input type="file" class="form-control" name="product_image[]" value="{{asset('storage/product_images/'.$images['product_images'])}}">
                        <button type="button" class="close pt-2" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endforeach
                    </div>
                    <div id="newElementId1"></div>
                    @error('product_image')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Featured</label>
                    <div class="input-group has-validation">
                    <select name="is_featured"  class="form-control">
                        <option value="0">Not Active</option>
                        <option value="1">Active</option>
                    </select>
                    </div>
                    @error('is_featured')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                <br>
                <a class="btn btn-success checked text-light float-right me-3"><i class="fas fa-plus"></i> Add Another Attribute Value</a>
                @foreach($productAttribute as  $productAttributes)
                <div class="row position-relative col-sm-12 clone alert alert-dismissible fade show pb-0 mb-0">
                    <div class="col-sm-5">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Attributes Name</label>
                        <div class="input-group has-validation">
                            <select name="attribute[]" class="form-control">
                                @foreach($attribute as $attributes)
                                    <option value="{{$attributes->id}}"
                                        <?php 
                                            if($attributes->id == $productAttributes->attribute_id){
                                                echo 'selected';
                                            }
                                        ?>
                                    >{{$attributes->attribute_name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Attributes Value</label>
                        <div class="input-group has-validation">
                            <input type="text" class="form-control" value="{{$productAttributes->attribute_value}}" name="attribute_value[]">
                        </div>
                    </div>
                    <div class="col-sm-2">
                    <button type="button" class="rounded btn btn-danger" style="height: 40px;margin-top: 30px;" data-dismiss="alert" aria-label="Close">
                        <i class="fas fa-trash"></i> Delete</button>
                    </div>
                    @error('attribute')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                @endforeach
                <div class="add-attribute-value"></div>
                <div class="col-sm-12 position-relative">
                    <label for="validationTooltip03" class="form-label"><span class="text-danger">*</span> Option Name</label>
                    <div class="input-group has-validation">
                        @foreach($option as $options)
                            <div class="me-2">
                                <input type="checkbox" value="{{$options->id}}" name="option[]"
                                <?php
                                foreach($productOption as $pro){
                                    if($options->id == $pro->option_id){
                                        echo 'checked';
                                    }
                                }
                                ?> >
                                <label for="">{{$options->option_name}}</label>
                            </div>
                        @endforeach
                    </div>
                    @error('option')
                        <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                    @enderror
                </div>
                    <div class="col-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-edit"> </i> Update</button>
                    </div>
                </form>
@endsection

resources/views/admin/products/listing.blade.php
@extends('layouts/admin_web')
<title>Skriper | Prdoucts</title>

@section('content')
    <div class="col-12 mb-3 d-flex justify-content-between">
        <h1>Products</h1>
        <?php 
            foreach (session()->get('permissionKey') as $key) {
                if($key['permission_key'] == 'product-add'){ 
        ?>

            <a href="{{ route('products.create') }}"><button class="btn btn-info my-3 text-light"><i class="fas fa-plus"></i> Add</button></a>
        <?php } }  ?>
    </div> 
    @if(Session::get('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{Session::get('success')}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    @endif
    @foreach($product as $products)
        <div class="col-4 mx-auto card" style="width:31%;">
            <img style="height:200px;" src="{{ asset('storage/product_images/'.$products['productImages'][0]['product_images']) }}" alt="">
            <div class="card-body">
                <h5 class="card-title">{{$products['product_name']}}</h5>
                <p class="card-text">{{substr($products['product_description'],0,100)}} ...</p>
                <div class="d-flex justify-content-between">
                    <a href="{{ route('products.show', $products['id']) }}"><button class="btn btn-primary"><i class="fas fa-eye"></i> View </button></a>
                    <?php 
                        foreach (session()->get('permissionKey') as $key) {
                            if($key['permission_key'] == 'product-update'){ 
                    ?>
                        <a href="{{ route('products.edit', $products['id']) }}"><button class="btn btn-success"><i class="fas fa-edit"></i> Edit </button></a>
                    <?php 
                        }
                        if($key['permission_key'] == 'product-delete'){ 
                    ?>
                        <form action="{{ route('products.destroy', $products['id']) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button>
                        </form>  
                    <?php } } ?>
                </div>
            </div>
        </div>
    @endforeach
        <div>
            {{$product->links('pagination/bootstrap-4')}}
        </div>
@endsection 

resources/views/admin/products/view.blade.php
@extends('layouts/admin_web')
@section('content')
@foreach($product as $products)
<title>Skriper | Products | {{$products['product_name']}}</title>


    <div class="col-12 mb-3 d-flex justify-content-between">
        <h1>Product <span class="text-secondary"> | {{$products['product_name']}}</span></h1>

    </div>
    <div class="mt-5 row">
        <div class="col-sm-4">
            <img id="expandedImg" style="width:100%;border: 2px solid darkgray;" src="{{ asset('storage/product_images/'.$products['productImages'][0]['product_images']) }}">
        </div>
        <div class="col-sm-8 my-auto">
            <h1 class="mb-4" style="font-size:60px;">{{$products['product_name']}}</h1>
            <p class="mb-4 fw-bold">{{$products['product_description']}}</p>
            <p class="fw-bold fs-5 m-0">Price : {{$products['price']}}</p>
            <span>
                @if($products['productImages'][0]['is_featured'] == 0) 
                    <span class="text-danger"><i class="fas fa-circle"></i>  Not Active</span> 
                @else 
                    <span class="text-success"><i class="fas fa-circle"></i> Active</span> 
                @endif
            </span>
            <p class="text-primary fw-bold m-0"><a href="{{$products['link']}}" target="_blank" class="text-decoration-none">Check out this {{$products['product_name']}}</a></p>
        </div>
        @foreach($products['productImages'] as $images)
            <div class="column">
                <img src="{{ asset('storage/product_images/'.$images['product_images']) }}" alt="Nature" style="width:100%;height:100px;" onclick="myFunction(this);">
            </div>
        @endforeach
    </div>
@endforeach

@endsection