routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\NotLoggedIn;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AllUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OptionController;
use App\Http\Controllers\OptionValueController;
use App\Http\Controllers\AttributeController;
use App\Http\Controllers\ProductAttributeController;
// use App\Http\Controllers\RolePermissionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login',[UserController::class,'login'])->middleware('notLoggedIn');

Route::post('/check',[UserController::class,'check'])->name('check');
Route::get('/logout',[UserController::class,'logout']);

Route::group(['middleware'=>'authCheck'], function (){
    Route::get('/admin',[UserController::class,'admin']);

    Route::resource('/admin/profile',ProfileController::class);
    Route::resource('/admin/users',AllUserController::class);
    Route::resource('/admin/roles',RoleController::class);
    Route::resource('/admin/permissions',PermissionController::class);
    Route::get('/admin/products/get-option-values',[ProductController::class,'getOptionValues']);
    Route::resource('/admin/products',ProductController::class);
   
    Route::resource('/admin/options',OptionController::class);
    Route::resource('/admin/option-values',OptionValueController::class);
    Route::resource('/admin/attributes',AttributeController::class);
    Route::resource('/admin/attribute-values',ProductAttributeController::class);
    // Route::resource('/admin/role_permissions',RolePermissionController::class);
});

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    use HasFactory;
    protected $table = 'permissions';

    public function permission(){
        return $this->hasMany('App\Models\RolePermission','permission_id','id');
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Permission;

class PermissionController extends Controller
{
    public function index(){
        $permission = Permission::all();
        // echo "<pre>";
        // print_r($permission);
        // exit();
        return view('admin/permissions/listing',compact('permission'));
    }

    public function create(){
        return view('admin/permissions/add');
    }

    public function store(Request $req){
        $req->validate([
            'permission_name'=>'required',
            'permission_module'=>'required',
            'permission_key'=>'required',
        ]);
        
        $permission = new Permission;
        $permission->permission_name = $req->permission_name;
        $permission->permission_module = $req->permission_module;
        $permission->permission_key = $req->permission_key;
        $permission->save();
        return redirect('/admin/permissions')->with('success','Permission is successfully added!');
    }

    public function show($id){

    }

    public function edit($id){
        $permission = Permission::find($id);
        return view('admin/permissions/edit',compact('permission'));
    }

    public function update(Request $req,$id){
        $req->validate([
            'permission_name'=>'required',
            'permission_module'=>'required',
            'permission_key'=>'required',
        ]);

        $permission = Permission::find($id);
        $permission->permission_name = $req->permission_name;
        $permission->permission_module = $req->permission_module;
        $permission->permission_key = $req->permission_key;
        $permission->save();
        return redirect('/admin/permissions')->with('success','Permission is successfully updated!');
    }

    public function destroy($id){
        $permission = Permission::find($id);
        $permission->delete();
        return redirect('/admin/permissions')->with('success','Permission is successfully deleted!');
    }
}

resources/views/admin/permissions/add.blade.php
@extends('layouts/admin_web')
<title>Skriper | Permissions | Add</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Add Permission</h1>
                </div>
                <form action="{{ route('permissions.store') }}" method="POST">
                    @csrf
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label">Permission Name</label>
                        <div class="input-group has-validation">
                        <input type="text" class="form-control" name="permission_name">
                        </div>
                        @error('permission_name')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label">Permission Module</label>
                        <div class="input-group has-validation">
                        <input type="text" class="form-control" name="permission_module">
                        </div>
                        @error('permission_module')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label">Permission Key</label>
                        <div class="input-group has-validation">
                        <input type="text" class="form-control" name="permission_key">
                        </div>
                        @error('permission_key')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-plus"></i> Add</button>
                    </div>
                </form> 
@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts/admin_web')
<title>Skriper | Permissions | Update</title>

@section('content')
                <div class="col-12 mb-3">
                    <h1>Update Permission</h1>
                </div>
                <form action="{{ route('permissions.update' , $permission->id) }}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label">Permission Name</label>
                        <div class="input-group has-validation">
                        <input type="text" class="form-control" name="permission_name" value="{{$permission->permission_name}}">
                        </div>
                        @error('permission_name')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label">Permission Modules</label>
                        <div class="input-group has-validation">
                            <input type="text" class="form-control" name="permission_module" value="{{$permission_module}}">
                        </div>
                        @error('permission_module')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-sm-12 position-relative">
                        <label for="validationTooltip03" class="form-label">Permission Key</label>
                        <div class="input-group has-validation">
                            <input type="text" class="form-control" name="permission_key" value="{{$permission_key}}">
                        </div>
                        @error('permission_key')
                            <span class="bg-danger p-2 text-light rounded">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-12 my-3">
                        <button class="btn btn-success" type="submit"><i class="fas fa-edit"> </i> Update</button>
                    </div>
                </form>
@endsection

resources/views/admin/permissions/listing.blade.php
@extends('layouts/admin_web')
<title>Skriper | Permissions</title>
@section('content')
                <div class="col-12 mb-3">
                <h1>Permissions</h1>
                    <!-- <a href="{{ route('permissions.create') }}"><button class="btn btn-info my-3 text-light"><i class="fas fa-plus"></i> Add</button></a> -->
                </div>
                @if(Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{Session::get('success')}}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                @endif
                <div class="card">
                <div class="headeing-content"><h5><i class="fal fa-list-ul me-1"></i> Permission List</h5></div>
                <div class="col-12">   
                <table id="userCategories" class="table table-responsive-sm table-hover table-bordered text-center">
                    <thead class="table-dark">
                        <tr>
                            <td>Id</td>
                            <td>Permission Name</td>
                            <td>Permissions Module</td>
                            <td>Permissions Key</td>
                            <!-- <td>Action</td> -->
                        </tr>
                    </thead>
                    <tbody class="table-secondary text-secondary">
                    @foreach($permission as $permissions)
                        <tr>
                            <td>{{$permissions->id}}</td>
                            <td>{{$permissions->permission_name}}</td>
                            <td>{{$permissions->permission_module}}</td>
                            <td>{{$permissions->permission_key}}</td>
                            <!-- <td class="d-flex"><a href="{{ route('permissions.edit', $permissions->id) }}" class="me-2"><button class="btn btn-success"><i class="fas fa-edit"></i> Edit </button></a>
                            <form action="{{ route('permissions.destroy', $permissions->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button>
                            </form>
                            </td> -->
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
                </div>
@endsection